# Generated by GPT-5.2 on 2026-05-05

from django.db import migrations, models


def set_diary_visible_to_friends(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(show_diary_to_friends=False).update(show_diary_to_friends=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_profile_show_diary_to_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_diary_to_friends',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_diary_visible_to_friends, reverse_code=noop_reverse),
    ]

