# Generated by GPT-5.2 on 2026-05-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diary', '0003_foodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='recipe_content_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recipe_food_entries',
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='recipe_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='servings',
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                help_text='Сколько порций рецепта было съедено (например 1.00).',
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='grams',
            field=models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='food_entries',
                to='diary.product',
            ),
        ),
        migrations.AddConstraint(
            model_name='foodentry',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(('product__isnull', False), ('recipe_content_type__isnull', True), ('recipe_object_id__isnull', True))
                    | models.Q(('product__isnull', True), ('recipe_content_type__isnull', False), ('recipe_object_id__isnull', False))
                ),
                name='foodentry_product_xor_recipe',
            ),
        ),
        migrations.AddConstraint(
            model_name='foodentry',
            constraint=models.CheckConstraint(
                condition=models.Q(('product__isnull', True)) | models.Q(('grams__isnull', False)),
                name='foodentry_grams_required_for_product',
            ),
        ),
        migrations.AddConstraint(
            model_name='foodentry',
            constraint=models.CheckConstraint(
                condition=models.Q(('recipe_content_type__isnull', True)) | models.Q(('servings__isnull', False)),
                name='foodentry_servings_required_for_recipe',
            ),
        ),
    ]

